#!/bin/bash
shopt -qs extglob

printUsage()
{
    add-signature --help 2>&1 | sed \
	-e "1s#^.*\$#Add my signature to the passed PDF document(s) (to the current working directory or TARGETDIR, with added *.${FAKESCAN_EXT:-scanned}.${ADDSIGNATURE_EXT:-signed}.pdf extension) so that it appears as if printed out, signed, and then rescanned.#" \
	-e '2b removeFirstParagraphLoop' \
	-e '/^Usage:$/N' -e '/\(^\|\n\)Usage: */{ s/\(^\|\n\)\(Usage: *\)\?\([^ ]\+ \)*add-signature /\1\2'"$(basename "$1")"' /; }' \
	-e '/^Example:$/N' -e '/\(^\|\n\)Example: */{ s/\(^\|\n\)\(Example: *\)\?add-signature /\1\2'"$(basename "$1") /; }" \
	-e b -e :removeFirstParagraphLoop -e '{ /\(^\|\n\)$/{ s/^\(.*\n\)\?//; b; }; N; b removeFirstParagraphLoop; }'
}

typeset -a addSignatureArgs=()
typeset -a tempdirPipeArgs=()
while [ $# -ne 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;

	--to|-o)	shift; tempdirPipeArgs+=(--output-dir "$1"); shift;;

	-+([rc]))	addSignatureArgs+=("$1"); shift;;
	--@(right|center))
			addSignatureArgs+=("$1"); shift;;
	-[%])		addSignatureArgs+=("$1" "$2"); shift; shift;;
	--@(geometry))	addSignatureArgs+=("$1" "$2"); shift; shift;;
	--)		shift; break;;
	*)		break;;
    esac
done
if [ $# -eq 0 ]; then
    printUsage "$0" >&2
    exit 2
fi

exec tempdirPipe --with-header "${tempdirPipeArgs[@]}" \
    --exec add-signature "${addSignatureArgs[@]}" --to '{O}' -- '{ii}' \; \
    --exec fakescan --to '{O}' -- '{ii}' \; \
    -- "$@"
