#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Converts (static or animated) GIF images to the modern (animated) PNG format.
HELPTEXT
    echo
    printf 'Usage: %q %s\n' "$(basename "$1")" '[--] GIF-INPUT-FILESPEC PNG-OUTPUT-FILESPEC [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
    --)			shift;;
esac
if [ $# -ne 2 ]; then
    printUsage "$0" >&2
    exit 2
fi
sourceFilespec="${1:?}"; shift
targetFilespec="${1:?}"; shift

# Determine whether the source is a static or animated GIF; ImageMagick can only
# extract individual images from the latter; we need the specialized gif2apng
# command for a conversion of animated GIFs.
# Source: https://davidwalsh.name/detect-gif-animated
if [ "$(identify -format %n -- "$sourceFilespec")" = 1 ]; then
    exec convert -- "$sourceFilespec" "$targetFilespec"
else
    if ! type -t gif2apng >/dev/null; then
	printf 'ERROR: %s is an animated GIF, but the required gif2apng program is not installed.\n' "$sourceFilespec"
	exit 3
    fi

    exec gif2apng -- "$sourceFilespec" "$targetFilespec"
fi
